# Google Colab 환경 구성 및 데이터 불러오기

In [ ]:
import os
import pandas as pd

In [ ]:
# 현재 경로에 있는 파일 확인하기

os.listdir('.')
# .config는 숨김파일

['.config', 'drive', 'sample_data']

In [ ]:
os.listdir('./drive/MyDrive')

['Colab Notebooks', '알파코']

In [ ]:
os.listdir('./drive/MyDrive/Colab Notebooks')

['알파코 파이썬 데이터 분석강의',
 'chromedriver.exe',
 '알파코',
 '연습문제',
 'Google Colab 환경 구성 및 데이터 불러오기 1109.ipynb',
 '거친코딩-파이썬 머신러닝',
 'Data']

In [ ]:
os.listdir('./drive/MyDrive/Colab Notebooks/Data')

['friend.csv',
 'crawlings__210510.log',
 'dolphine.jpg',
 'test_csv.txt',
 'Naver_opinion.txt',
 'abalone.data',
 'NanumBarunGothic.ttf',
 'new_friend_index_true.csv',
 'new_friend.csv',
 'test.csv',
 'train_data.csv',
 'train.csv']

In [ ]:
# 데이터 폴더 src 변수 할당
base_src = './drive/MyDrive/Colab Notebooks/Data'

# friend.csv 파일 src 변수할당
friend_src = base_src + '/friend.csv'

In [ ]:
# pandas의 read_csv -> csv파일 데이터 불러오기
df = pd.read_csv(friend_src, encoding='utf-8')

# 안되는 경우 뒤에 engine='python' 붙여보기

In [ ]:
# head() -> 앞의 5개 데이터 읽어보기
df.head()

    name  age        job
0   John   20    student
1  Jenny   30  developer
2   Nate   30    teacher
3  Julia   40    dentist
4  Brian   45    manager

In [ ]:
df

    name  age        job
0   John   20    student
1  Jenny   30  developer
2   Nate   30    teacher
3  Julia   40    dentist
4  Brian   45    manager
5  Chris   25     intern

In [ ]:
# 읽어온 데이터 저장
new_friend_src = base_src +"/new_friend.csv"

In [ ]:
# index False 필수
df.to_csv(new_friend_src, index=False, encoding='utf-8')

In [ ]:
os.listdir(base_src)
# new friend 생성됨

['friend.csv',
 'crawlings__210510.log',
 'dolphine.jpg',
 'test_csv.txt',
 'Naver_opinion.txt',
 'abalone.data',
 'NanumBarunGothic.ttf',
 'test.csv',
 'train_data.csv',
 'train.csv',
 'new_friend.csv']

In [18]:
new_friend_src = base_src +"/new_friend_index_true.csv"
df.to_csv(new_friend_src, encoding='utf-8')
os.listdir(base_src)

# new_friend_index_true.csv 생성됨

['friend.csv',
 'crawlings__210510.log',
 'dolphine.jpg',
 'test_csv.txt',
 'Naver_opinion.txt',
 'abalone.data',
 'NanumBarunGothic.ttf',
 'test.csv',
 'train_data.csv',
 'train.csv',
 'new_friend.csv',
 'new_friend_index_true.csv']

In [19]:
new_friend_index_true = pd.read_csv(new_friend_src)
new_friend_index_true
# 인덱스를 또 만들어줌 쓸데 없다.

   Unnamed: 0   name  age        job
0           0   John   20    student
1           1  Jenny   30  developer
2           2   Nate   30    teacher
3           3  Julia   40    dentist
4           4  Brian   45    manager
5           5  Chris   25     intern

In [21]:
pd.Series([1,2,3], index=['가','나','다'])

# 인덱스 사용이유 = 조회, 데이터 정렬

가    1
나    2
다    3
dtype: int64

# Series 및 DataFrame 실습

In [22]:
import numpy as np

### Series

In [23]:
pd.Series([1,2,3])
# 인덱스가 있다.

0    1
1    2
2    3
dtype: int64

In [24]:
np.array([1,2,3])
# 인덱스가 없다.

array([1, 2, 3])

In [25]:
df

    name  age        job
0   John   20    student
1  Jenny   30  developer
2   Nate   30    teacher
3  Julia   40    dentist
4  Brian   45    manager
5  Chris   25     intern

In [27]:
# 데이터프레임(집합) -> 시리즈(단일)
# 데이터프레임의 한 열 = 시리즈
series = df['name']
series

0     John
1    Jenny
2     Nate
3    Julia
4    Brian
5    Chris
Name: name, dtype: object

In [28]:
# pd.Series 함수를 통해서 만드는 것도 가능
series = pd.Series([1,2,3,4])
series

0    1
1    2
2    3
3    4
dtype: int64

In [29]:
series =pd.Series([1,2,3,4], index=['a','b','c','d'], dtype=float)
series

a    1.0
b    2.0
c    3.0
d    4.0
dtype: float64

In [32]:
series = pd.Series([10,2,5,4],index=['a','b','c','d'], dtype=float)
series

a    10.0
b     2.0
c     5.0
d     4.0
dtype: float64

In [33]:
series.sort_values(ascending=True)
# 오름차

b     2.0
d     4.0
c     5.0
a    10.0
dtype: float64

In [35]:
series
# 변수 할당을 안해줘서 그대로임

a    10.0
b     2.0
c     5.0
d     4.0
dtype: float64

In [37]:
series = series.sort_values(ascending=False)
series
# 내림차 변수할당

a    10.0
c     5.0
d     4.0
b     2.0
dtype: float64

### DataFrame

In [46]:
# 변수명은 관련된 이름으로 하는게 좋음
df = pd.DataFrame({'a':[2,3],'b':[5,10]})
df

   a   b
0  2   5
1  3  10

In [42]:
# raw data 가공처리 할 때 df= pd.DataFrame()으로 빈 데이터프레임 만들고 df=pd.concat([df,df_new],axis=0) 쌓아줌
df = pd.DataFrame([[2,5],[3,10],[10,20]],columns=['a','b'])
df
# row 방향으로 쌓아짐

    a   b
0   2   5
1   3  10
2  10  20

In [45]:
df = pd.DataFrame([[2,5,100],[3,10,200],[10,20,300]],columns=['a','b','c'], index=['가','나','다'], dtype=float)
df

      a     b      c
가   2.0   5.0  100.0
나   3.0  10.0  200.0
다  10.0  20.0  300.0

# DataFrame 행,열 필터링 & 삭제 & 수정

In [74]:
df= pd.read_csv(friend_src,encoding='utf-8')
df.head()

    name  age        job
0   John   20    student
1  Jenny   30  developer
2   Nate   30    teacher
3  Julia   40    dentist
4  Brian   45    manager

In [48]:
# index 2번에 해당하는 row 가져오기
df.iloc[2]

# series

name       Nate
age          30
job     teacher
Name: 2, dtype: object

In [49]:
# 4번을 데이터프레임으로 가져오기
df.iloc[[4]]

    name  age      job
4  Brian   45  manager

In [50]:
# 특정 컬럼만 보기
df['job']

0      student
1    developer
2      teacher
3      dentist
4      manager
5       intern
Name: job, dtype: object

In [51]:
# 행,열
df.loc[:,'job'] # 중요

0      student
1    developer
2      teacher
3      dentist
4      manager
5       intern
Name: job, dtype: object

In [52]:
df.iloc[:,2] # 중요

0      student
1    developer
2      teacher
3      dentist
4      manager
5       intern
Name: job, dtype: object

In [56]:
# developer 만 가져오고 싶다.
df.iloc[1,2]

'developer'

In [57]:
# row만은 자를 수 있지만 컬럼 만은 자를 수 없음
df.iloc[2:4]

    name  age      job
2   Nate   30  teacher
3  Julia   40  dentist

In [58]:
df.iloc[:,:2]

    name  age
0   John   20
1  Jenny   30
2   Nate   30
3  Julia   40
4  Brian   45
5  Chris   25

### DataFrame 필터링

In [76]:
# age가 30 이상인 경우만 가져오기
df[df['age']>=30]

    name  age        job
1  Jenny   30  developer
2   Nate   30    teacher
3  Julia   40    dentist
4  Brian   45    manager

In [77]:
# job 이 intern인 사람 가져오기
df[df['job']=='intern']

    name  age     job
5  Chris   25  intern

In [83]:
# 조건이 여러개
# 30이상 40대 이하 teacher
# 조건을 하나씩 괄호로 묶어줘야함.
df[(df['age']>=30) & (df['age']<=40) & (df['job']=='teacher')]

   name  age      job
2  Nate   30  teacher

In [85]:
# 30대 미만 혹은 40대 초과
df[(df['age']<30) | (df['age']>40)]

    name  age      job
0   John   20  student
4  Brian   45  manager
5  Chris   25   intern

In [95]:
# in 으로 포함 조건 걸기
# in으로 확인할 값은 하나여야함
# 두개를 확인하고 싶으면
df[df['job'].apply(lambda x : x in ['student','manager'])]

# df['job'] 값 하나씩을 x 에 넣어 주고 ['student','manager']에 포함 되는지 확인 (T/F)

    name  age      job
0   John   20  student
4  Brian   45  manager

### DataFrame 행, 열 삭제, 수정

In [96]:
# df 복사해두기 (원본 데이터 유지)
temp = df.copy()
temp

    name  age        job
0   John   20    student
1  Jenny   30  developer
2   Nate   30    teacher
3  Julia   40    dentist
4  Brian   45    manager
5  Chris   25     intern

In [60]:
df= pd.DataFrame(np.arange(12).reshape(3,4),columns=['A','B','C','D'])
df

   A  B   C   D
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [61]:
df.drop(['B','C'],axis=1)
# axis =1 -> 세로 (1은 세로)

   A   D
0  0   3
1  4   7
2  8  11

In [63]:
df

   A  B   C   D
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [64]:
df.drop(['B','C'],axis=1,inplace=True)

In [65]:
df

   A   D
0  0   3
1  4   7
2  8  11

In [66]:
df.drop([0])
# axis=0이 디폴트

   A   D
1  4   7
2  8  11

In [67]:
df

   A   D
0  0   3
1  4   7
2  8  11

In [69]:
df.loc[1,'D']='럭키~'
df

   A    D
0  0    3
1  4  럭키~
2  8   11

In [70]:
df.iloc[1,1]='woo~'
df

   A     D
0  0     3
1  4  woo~
2  8    11

In [71]:
df.iloc[:,0]="good"
df

      A     D
0  good     3
1  good  woo~
2  good    11

In [72]:
df.loc[:,:]="done!"
df

       A      D
0  done!  done!
1  done!  done!
2  done!  done!

# DataFrame 그룹 생성(groupby)

In [97]:
os.listdir(base_src)

['friend.csv',
 'crawlings__210510.log',
 'dolphine.jpg',
 'test_csv.txt',
 'Naver_opinion.txt',
 'abalone.data',
 'NanumBarunGothic.ttf',
 'test.csv',
 'train_data.csv',
 'train.csv',
 'new_friend.csv',
 'new_friend_index_true.csv']

In [98]:
abalone_src = base_src+'/abalone.data'

In [102]:
abalone_df = pd.read_csv(abalone_src, header=None, sep=',', names=['sex','length','diameter','height', 
                  'whole_weight','shucked_weight','viscera_weight', 
                  'shell_weight','rings'])
abalone_df
# header는 안가져옴 ,기준으로 컬럼 나누기, names는 컬럼명

,sex,length,diameter,height,whole_weight,shucked_weight,viscera_weight,shell_weight,rings
0,M,0.455,0.365,0.095,0.5140,0.2245,0.1010,0.1500,15
1,M,0.350,0.265,0.090,0.2255,0.0995,0.0485,0.0700,7
2,F,0.530,0.420,0.135,0.6770,0.2565,0.1415,0.2100,9
3,M,0.440,0.365,0.125,0.5160,0.2155,0.1140,0.1550,10
4,I,0.330,0.255,0.080,0.2050,0.0895,0.0395,0.0550,7
...,...,...,...,...,...,...,...,...,...
4172,F,0.565,0.450,0.165,0.8870,0.3700,0.2390,0.2490,11
4173,M,0.590,0.440,0.135,0.9660,0.4390,0.2145,0.2605,10
4174,M,0.600,0.475,0.205,1.1760,0.5255,0.2875,0.3080,9
4175,F,0.625,0.485,0.150,1.0945,0.5310,0.2610,0.2960,10
4176,M,0.710,0.555,0.195,1.9485,0.9455,0.3765,0.4950,12

In [103]:
# 데이터 shape 확인
abalone_df.shape
# 딥러닝에서 이미지(데이터수 , 가로, 세로, 채널) -> 4차원이다.
# 모양을 알기 위해

(4177, 9)

In [105]:
# 데이터 결측값 확인
abalone_df.isnull().sum()

sex               0
length            0
diameter          0
height            0
whole_weight      0
shucked_weight    0
viscera_weight    0
shell_weight      0
rings             0
dtype: int64

In [106]:
abalone_df.isnull().sum().sum()

0

In [107]:
# 기술 통계 확인
abalone_df.describe()
# 문자열 컬럼은 나오지 않는다. (연속형 변수(Numeric)만 확인 )

,length,diameter,height,whole_weight,shucked_weight,viscera_weight,shell_weight,rings
count,4177.000000,4177.000000,4177.000000,4177.000000,4177.000000,4177.000000,4177.000000,4177.000000
mean,0.523992,0.407881,0.139516,0.828742,0.359367,0.180594,0.238831,9.933684
std,0.120093,0.099240,0.041827,0.490389,0.221963,0.109614,0.139203,3.224169
min,0.075000,0.055000,0.000000,0.002000,0.001000,0.000500,0.001500,1.000000
25%,0.450000,0.350000,0.115000,0.441500,0.186000,0.093500,0.130000,8.000000
50%,0.545000,0.425000,0.140000,0.799500,0.336000,0.171000,0.234000,9.000000
75%,0.615000,0.480000,0.165000,1.153000,0.502000,0.253000,0.329000,11.000000
max,0.815000,0.650000,1.130000,2.825500,1.488000,0.760000,1.005000,29.000000

In [110]:
# 전복(abalone) 성별에 따라 groupby 함수를 통해 집계
# whole_weight 값들을 성별로 나눈다. 그 후 집계 함수를 적용
grouped = abalone_df['whole_weight'].groupby(abalone_df['sex'])
grouped.sum()
# 성별 별의 whole_weight 합

sex
F    1367.8175
I     578.8885
M    1514.9500
Name: whole_weight, dtype: float64

In [111]:
# 성별 별의 whole_weight 평균
grouped.mean()

sex
F    1.046532
I    0.431363
M    0.991459
Name: whole_weight, dtype: float64

In [112]:
grouped.size()
# i 는 무게가 작다.

sex
F    1307
I    1342
M    1528
Name: whole_weight, dtype: int64

In [113]:
# 그룹 변수가 하나가 아닌 전체 연속형 변수에 대한 집계
abalone_df.groupby(abalone_df['sex']).mean()
# 전체 데이터에 대한 성별 별 평균

,length,diameter,height,whole_weight,shucked_weight,viscera_weight,shell_weight,rings
sex,,,,,,,,
F,0.579093,0.454732,0.158011,1.046532,0.446188,0.230689,0.302010,11.129304
I,0.427746,0.326494,0.107996,0.431363,0.191035,0.092010,0.128182,7.890462
M,0.561391,0.439287,0.151381,0.991459,0.432946,0.215545,0.281969,10.705497

In [114]:
# 간단하게 표현 가능
abalone_df.groupby('sex').mean()

,length,diameter,height,whole_weight,shucked_weight,viscera_weight,shell_weight,rings
sex,,,,,,,,
F,0.579093,0.454732,0.158011,1.046532,0.446188,0.230689,0.302010,11.129304
I,0.427746,0.326494,0.107996,0.431363,0.191035,0.092010,0.128182,7.890462
M,0.561391,0.439287,0.151381,0.991459,0.432946,0.215545,0.281969,10.705497

In [117]:
# 새로운 조건에 맞는 변수 추가
abalone_df['length_bool'] = np.where(abalone_df['length']>abalone_df['length'].median(), # 중간값 보다 큰가?
                                     'length_long'# True 일 경우
                                     ,'length_short') # False 일 경우
abalone_df
# np.where은 조건에 맞는 인덱스를 반환해준다. np.where(a,b,c) 일때
# a는 조건 (b는 True 일 때의 값 / c는 False일 때의 값이다.) 
# a는 array 형태

,sex,length,diameter,height,whole_weight,shucked_weight,viscera_weight,shell_weight,rings,length_bool
0,M,0.455,0.365,0.095,0.5140,0.2245,0.1010,0.1500,15,length_short
1,M,0.350,0.265,0.090,0.2255,0.0995,0.0485,0.0700,7,length_short
2,F,0.530,0.420,0.135,0.6770,0.2565,0.1415,0.2100,9,length_short
3,M,0.440,0.365,0.125,0.5160,0.2155,0.1140,0.1550,10,length_short
4,I,0.330,0.255,0.080,0.2050,0.0895,0.0395,0.0550,7,length_short
...,...,...,...,...,...,...,...,...,...,...
4172,F,0.565,0.450,0.165,0.8870,0.3700,0.2390,0.2490,11,length_long
4173,M,0.590,0.440,0.135,0.9660,0.4390,0.2145,0.2605,10,length_long
4174,M,0.600,0.475,0.205,1.1760,0.5255,0.2875,0.3080,9,length_long
4175,F,0.625,0.485,0.150,1.0945,0.5310,0.2610,0.2960,10,length_long
4176,M,0.710,0.555,0.195,1.9485,0.9455,0.3765,0.4950,12,length_long

In [118]:
# 그룹변수를 2개 이상 선택해서 총계 처리
abalone_df.groupby(['sex','length_bool']).mean()
# EDA (Exploratory Data Analysis)

                    length  diameter    height  whole_weight  shucked_weight  \
sex length_bool
F   length_long   0.626895  0.493020  0.169944      1.261330        0.542957
    length_short  0.477428  0.373301  0.132632      0.589702        0.240380
I   length_long   0.584495  0.452952  0.150957      0.923215        0.402524
    length_short  0.402210  0.305893  0.100997      0.351234        0.156581
M   length_long   0.623359  0.489291  0.168670      1.255182        0.554312
    length_short  0.454875  0.353336  0.121664      0.538157        0.224335

                  viscera_weight  shell_weight      rings
sex length_bool
F   length_long         0.276945      0.360013  11.415073
    length_short        0.132311      0.178650  10.521531
I   length_long         0.196912      0.273247  10.585106
    length_short        0.074920      0.104549   7.451473
M   length_long         0.272203      0.351683  11.299172
    length_short        0.118156      0.162141   9.685053

In [119]:
# 간결하게 표현
abalone_df.groupby(['sex','length_bool'])['whole_weight'].mean()
# whole_weight에 대한 것만 보기

sex  length_bool
F    length_long     1.261330
     length_short    0.589702
I    length_long     0.923215
     length_short    0.351234
M    length_long     1.255182
     length_short    0.538157
Name: whole_weight, dtype: float64